name: heavyweight_app
description: Mandate-driven fitness tracking with brutal honesty.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version:  1.0.0+2

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_weight_picker: ^1.0.3
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  connectivity_plus: ^6.0.5
  country_code_picker: ^3.1.0
  dropdown_button2: 2.3.9
  file_picker: ^8.1.4
  flutter_animate: ^4.5.2
  flutter_cache_manager: ^3.4.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_plugin_android_lifecycle: ^2.0.23
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_path: ^0.7.4
  mime_type: ^1.0.1
  page_transition: 2.1.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  provider: ^6.1.2
  readmore: ^3.0.0
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.4.1
  stop_watch_timer: ^3.2.1
  supabase_flutter: ^2.8.0
  table_calendar: ^3.1.2
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dependency_overrides:
  uuid: ^4.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  image: ^4.3.0
  lints: ^5.0.0

  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - env.json
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  fonts:
    - family: 'Rubik'
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900

    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

